using IronPdf.Engines.Chrome;
using IronPdf;
namespace IronPdf.Examples.HowTo.JavascriptToPdf
{
    public static class Section1
    {
        public static void Run()
        {
            new IronPdf.ChromePdfRenderer { RenderingOptions = { EnableJavaScript = true, WaitFor = IronPdf.Rendering.WaitFor.JavaScript() } }
                .RenderHtmlAsPdf("<h1>Start</h1><script>document.write('<h1>Generated by JS</h1>');window.ironpdf.notifyRender();</script>")
                .SaveAs("js‑rendered.pdf");
        }
    }
}