using IronPdf;
using IronPdf.Examples.Tutorial.CsharpEditPdfCompleteTutorial;


Section1.Run();
// Section10.Run();
// Section11.Run();
// Section12.Run();
// Section13.Run();
// Section14.Run();
// Section15.Run();
// Section16.Run();
// Section17.Run();
// Section18.Run();
// Section19.Run();
// Section2.Run();
// Section20.Run();
// Section21.Run();
// Section22.Run();
// Section23.Run();
// Section24.Run();
// Section25.Run();
// Section26.Run();
// Section27.Run();
// Section28.Run();
// Section3.Run();
// Section4.Run();
// Section5.Run();
// Section6.Run();
// Section7.Run();
// Section8.Run();
// Section9.Run();
